services:

  app:
    restart: always
    container_name: app_bf
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres

  postgres:
    restart: always
    container_name: postgres_bf
    image: postgres:15
    volumes:
      - postgres_ii_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -V" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: -p ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  migrations:
    build:
      context: .
      dockerfile: Dockerfile_migrations
    env_file:
      - .env
    depends_on:
      - postgres
    command: alembic upgrade head

volumes:
  postgres_ii_volume:

